version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_KEY: ${API_KEY}
    command: streamlit run landingpage.py
    volumes:
      - .:/app
    ports:
      - "7100:8501"

